apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec: 
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      labels: 
        component: mongodb
    spec:
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-persistent-volume-claim
      containers:
      - name: mongodb 
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongodb-storage
            mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
spec:
  type: ClusterIP
  selector:
    component: mongodb
  ports:
  - port: 27017
    targetPort: 27017
