apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels: 
        component: postgres
    spec:
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-persistent-volume-claim
      containers:
      - name: postgres 
        image: postgres
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
            subPath: postgres
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DATABASE
            value: online_boutique
        lifecycle:
            postStart:
              exec:
                command:
                  - '/bin/sh'
                  - '-c'
                  - >
                    until psql -U $POSTGRES_USER -c '\l'; do
                      echo >&2 "$(date +%Y%m%dt%H%M%S) Postgres is unavailable - sleeping"
                      sleep 1
                    done;
                    psql -U $POSTGRES_USER -c "create database ${POSTGRES_DATABASE}";
                    psql -U $POSTGRES_USER $POSTGRES_DATABASE < schema.sql;
---
apiVersion: v1
kind: Service
metadata:
  name: postgresservice
spec:
  type: ClusterIP
  selector:
    component: postgres
  ports:
  - port: 5432
    targetPort: 5432