apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapiservice
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: restapiservice
  template:
    metadata:
      labels:
        app: restapiservice
    spec:
      containers:
        - name: server
          image: restapiservice
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_HOST
              value: postgresservice
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: online_boutique
            - name: POSTGRES_PASSWORD
              value: any_password
---
apiVersion: v1
kind: Service
metadata:
  name: restapiservice
spec:
  type: ClusterIP
  selector:
    app: restapiservice
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: restapiservice-external
spec:
  type: LoadBalancer
  selector:
    app: restapiservice
  ports:
  - name: http
    port: 80
    targetPort: 5000

